name: Build release Docker image

on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when I create or push a `release/**` branch
  push:
    branches:
      - feature/docker

env:
  DOCKER_IMAGE_NAME: my-image
  DOCKER_REGISTRY_URL: dockerhub.com

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    # Runner to use
    runs-on: ubuntu-latest
    environment: Docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          context: ./docker/python-web-app/

      - name: List files in context
        run: |
          ls -la ./docker/python-web-app
        

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/python-web-app
          dockerfile: random.Dockerfile
          push: true
          tags: practise